name: autocare_brasil
description: AutoCare Brasil
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # Navegação
  go_router: ^17.3.0

  # Banco de Dados
  sqflite: ^2.4.3
  path: ^1.9.1
  path_provider: ^2.1.6

  # Estado
  flutter_riverpod: ^2.6.1

  # Datas
  intl: ^0.20.3

  # Gráficos
  fl_chart: ^1.2.0

  # Ícones
  font_awesome_flutter: ^10.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/